### ISSUE TITLE
Add pre-built kernels

### ISSUE THREAD

**Issue by jaylinski** [sonyxperiadev/kernel-sony-msm-4.14-common#5]
Hi! Are going to add pre-built kernels? (Like in https://github.com/sonyxperiadev/kernel-sony-msm-4.9-common)
If yes, when will you add them?

**Comment by jerpelea** [comment]
prebuilt kernels will be added when we will enter the beta release

**Comment by jaylinski** [comment]
@jerpelea Thanks for the info! Do you have an ETA?
